name: RuneCosmetics
version: '1.0-SNAPSHOT'
main: com.realgotqkura.runeCosmetics.RuneCosmetics
api-version: '1.21'

commands:
  runes:
    description: Opens the RuneCosmetics gui
    permission: RuneCosmetics.op
  runes_debug:
    permission: RuneCosmetics.op
